/**This class is automatically generated by LayaAirIDE, please do not make any modifications. */
import seat from "./game/GameCenter/seat"
import GameUI from "./game/GameCenter/GameUI"
import setSceneWH from "./game/common/setSceneWH"
import GameControl from "./game/GameCenter/GameControl"
/*
* 游戏初始化配置;
*/
export default class GameConfig{
    static width:number=1242;
    static height:number=2208;
    static scaleMode:string="fixedwidth";
    static screenMode:string="none";
    static alignV:string="top";
    static alignH:string="left";
    static startScene:any="Game.scene";
    static sceneRoot:string="";
    static debug:boolean=false;
    static stat:boolean=false;
    static physicsDebug:boolean=false;
    static exportSceneToJson:boolean=true;
    constructor(){}
    static init(){
        var reg: Function = Laya.ClassUtils.regClass;
        reg("game/GameCenter/seat.ts",seat);
        reg("game/GameCenter/GameUI.ts",GameUI);
        reg("game/common/setSceneWH.ts",setSceneWH);
        reg("game/GameCenter/GameControl.ts",GameControl);
    }
}
GameConfig.init();